---
- hosts: web

  become: yes

  tasks:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add User
      user:
        name: ec2-user
        groups: docker
        append: yes